# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Cache@2
  inputs:
    key: 'pods | "$(Agent.OS)" | Podfile.lock'
    path: '$(System.DefaultWorkingDirectory)/Pods'
    cacheHitVar: 'PODS_CACHE_RESTORED'
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
  condition: and(succeeded(), ne(variables.PODS_CACHE_RESTORED, 'true'))
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'karlosarr'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      sonar.cfamily.build-wrapper-output="build_wrapper_output_directory"
- task: CmdLine@2
  displayName: "Sonar Wrapper"
  inputs:
    script: |
      wget https://sonarcloud.io/static/cpp/build-wrapper-macosx-x86.zip
      unzip build-wrapper-macosx-x86.zip
      ls build-wrapper-macosx-x86
      build-wrapper-macosx-x86/build-wrapper-macosx-x86 --out-dir build_wrapper_output_directory xcodebuild clean build -workspace SwiftAppiOS.xcworkspace -scheme SwiftAppiOS -configuration Release -sdk 'iphoneos' CODE_SIGNING_ALLOWED=NO
- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'SwiftAppiOS.xcworkspace'
    scheme: 'SwiftAppiOS'
    packageApp: false